//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebasDemo.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PruebasDemo.Application.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creando nuevo crédito con ID: {CreditoId}.
        /// </summary>
        public static string CreditCreateLog {
            get {
                return ResourceManager.GetString("CreditCreateLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El crédito no está activo.
        /// </summary>
        public static string CreditNotActive {
            get {
                return ResourceManager.GetString("CreditNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crédito no encontrado.
        /// </summary>
        public static string CreditNotFound {
            get {
                return ResourceManager.GetString("CreditNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los meses deben ser mayor a cero..
        /// </summary>
        public static string MonthMustBePositive {
            get {
                return ResourceManager.GetString("MonthMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto debe ser mayor a cero..
        /// </summary>
        public static string AmountMustBePositive {
            get {
                return ResourceManager.GetString("AmountMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto de pago excede el saldo del crédito.
        /// </summary>
        public static string PaymentExceedsBalance {
            get {
                return ResourceManager.GetString("PaymentExceedsBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago realizado para el crédito con ID: {CreditoId}, Monto: {MontoPago}.
        /// </summary>
        public static string PaymentMade {
            get {
                return ResourceManager.GetString("PaymentMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El monto de pago debe ser mayor a cero.
        /// </summary>
        public static string PaymentMustBePositive {
            get {
                return ResourceManager.GetString("PaymentMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crédito creado exitosamente.
        /// </summary>
        public static string SuccessCreated {
            get {
                return ResourceManager.GetString("SuccessCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crédito eliminado exitosamente.
        /// </summary>
        public static string SuccessDeleted {
            get {
                return ResourceManager.GetString("SuccessDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crédito encontrado.
        /// </summary>
        public static string SuccessFound {
            get {
                return ResourceManager.GetString("SuccessFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créditos obtenidos correctamente.
        /// </summary>
        public static string SuccessGet {
            get {
                return ResourceManager.GetString("SuccessGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago realizado correctamente.
        /// </summary>
        public static string SuccessPayment {
            get {
                return ResourceManager.GetString("SuccessPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crédito actualizado exitosamente.
        /// </summary>
        public static string SuccessUpdated {
            get {
                return ResourceManager.GetString("SuccessUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La tasa de interés no puede ser negativa..
        /// </summary>
        public static string RateMustBePositive {
            get {
                return ResourceManager.GetString("RateMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errores de validación.
        /// </summary>
        public static string ValidationErrors {
            get {
                return ResourceManager.GetString("ValidationErrors", resourceCulture);
            }
        }
    }
}
